server:
  port: 8090
  servlet:
    context-path: /springboot-mybatis

#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&amp&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


#mybatis
mybatis:
  type-aliases-package: com.zd.demo.dao.entity
  mapper-locations: classpath:mapper/*.xml
  #configuration: classpath:/mybatis-config.xml

